package image

import (
	"encoding/base64"
	"fmt"
	"path/filepath"
	"strings"
)

type CACertConfig struct {
	InstallCmd string
	CertDir    string
	UpdateCmd  string
	// BundlePath is the single-file CA bundle regenerated by UpdateCmd and
	// used as the target for SSL_CERT_FILE & friends.
	BundlePath string
	// TrustDir is the hashed certificate directory honored by OpenSSL-style
	// consumers via SSL_CERT_DIR.
	TrustDir string
}

func GetCACertConfig(os OSFamily) CACertConfig {
	switch os {
	case OSAlpine:
		return CACertConfig{
			InstallCmd: "apk add --no-cache --no-check-certificate ca-certificates",
			CertDir:    "/usr/local/share/ca-certificates",
			UpdateCmd:  "update-ca-certificates",
			BundlePath: "/etc/ssl/cert.pem",
			TrustDir:   "/etc/ssl/certs",
		}
	case OSDebian, OSUbuntu:
		return CACertConfig{
			InstallCmd: "apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update && apt-get install -y --allow-unauthenticated -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false ca-certificates",
			CertDir:    "/usr/local/share/ca-certificates",
			UpdateCmd:  "update-ca-certificates",
			BundlePath: "/etc/ssl/certs/ca-certificates.crt",
			TrustDir:   "/etc/ssl/certs",
		}
	case OSCentOS, OSFedora, OSRHEL, OSRocky, OSAlmaLinux, OSAmazonLinux:
		return CACertConfig{
			InstallCmd: "yum install -y --nogpgcheck --setopt=sslverify=0 ca-certificates",
			CertDir:    "/etc/pki/ca-trust/source/anchors",
			UpdateCmd:  "update-ca-trust extract",
			BundlePath: "/etc/pki/tls/certs/ca-bundle.crt",
			TrustDir:   "/etc/pki/tls/certs",
		}
	case OSArch:
		return CACertConfig{
			InstallCmd: "pacman -Sy --noconfirm ca-certificates",
			CertDir:    "/etc/ca-certificates/trust-source/anchors",
			UpdateCmd:  "trust extract-compat",
			BundlePath: "/etc/ssl/certs/ca-certificates.crt",
			TrustDir:   "/etc/ssl/certs",
		}
	case OSOpenSUSE, OSSLES:
		return CACertConfig{
			InstallCmd: "zypper --non-interactive install ca-certificates",
			CertDir:    "/usr/share/pki/trust/anchors",
			UpdateCmd:  "update-ca-certificates",
			BundlePath: "/etc/ssl/ca-bundle.pem",
			TrustDir:   "/etc/ssl/certs",
		}
	default:
		return CACertConfig{
			InstallCmd: "apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update && apt-get install -y --allow-unauthenticated -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false ca-certificates",
			CertDir:    "/usr/local/share/ca-certificates",
			UpdateCmd:  "update-ca-certificates",
			BundlePath: "/etc/ssl/certs/ca-certificates.crt",
			TrustDir:   "/etc/ssl/certs",
		}
	}
}

// caCertEnvLines sets environment variables that make language runtimes trust
// the OS CA bundle regenerated with the injected certificates:
//   - SSL_CERT_FILE / SSL_CERT_DIR: Python (ssl, urllib, requests), Go,
//     Rust (native-tls / rustls-native-certs), curl, git
//   - CURL_CA_BUNDLE: curl's alternative override
//   - REQUESTS_CA_BUNDLE: Python requests (certifi replacement)
//   - PIP_CERT: pip
//   - NODE_EXTRA_CA_CERTS: Node.js (additive to its bundled roots)
//
// Java is covered by the distro integration: on Debian-family images
// update-ca-certificates regenerates $JAVA_HOME/lib/security/cacerts via the
// ca-certificates-java hook, and RHEL-family update-ca-trust regenerates
// /etc/pki/java/cacerts.
func caCertEnvVars(bundlePath, trustDir string) []string {
	return []string{
		"SSL_CERT_FILE=" + bundlePath,
		"SSL_CERT_DIR=" + trustDir,
		"CURL_CA_BUNDLE=" + bundlePath,
		"REQUESTS_CA_BUNDLE=" + bundlePath,
		"PIP_CERT=" + bundlePath,
		"NODE_EXTRA_CA_CERTS=" + bundlePath,
	}
}

func caCertEnvLines(bundlePath, trustDir string) []string {
	vars := caCertEnvVars(bundlePath, trustDir)
	lines := make([]string, 0, len(vars))
	for _, v := range vars {
		lines = append(lines, "ENV "+v)
	}
	return lines
}

// GenerateCACertInlineLines emits install + inline-write + update RUN lines.
// Cert content is embedded base64 (no COPY, no context files needed), for
// frontends that receive rules but cannot add files to the build context.
func GenerateCACertInlineLines(certContents map[string][]byte, os OSFamily) []string {
	if len(certContents) == 0 {
		return nil
	}
	cfg := GetCACertConfig(os)
	var lines []string

	lines = append(lines, "# --- injected by whalevet: install ca-certificates package ---")
	lines = append(lines, "RUN "+cfg.InstallCmd)

	lines = append(lines, "# --- injected by whalevet: install custom CA certificates (inline) ---")
	for name, content := range certContents {
		b64 := base64.StdEncoding.EncodeToString(content)
		lines = append(lines, fmt.Sprintf("RUN mkdir -p %s && echo '%s' | base64 -d > %s/%s && chmod 644 %s/%s",
			cfg.CertDir, b64, cfg.CertDir, name, cfg.CertDir, name))
	}

	lines = append(lines, "# --- injected by whalevet: set CA bundle env vars ---")
	lines = append(lines, caCertEnvLines(cfg.BundlePath, cfg.TrustDir)...)

	return lines
}

// CertTargetName returns the filename under which a cert must be installed:
// basename with a .crt extension, since update-ca-certificates (and its
// counterparts) only pick up *.crt files.
func CertTargetName(path string) string {
	base := filepath.Base(path)
	return strings.TrimSuffix(base, filepath.Ext(base)) + ".crt"
}

func GenerateCACertDockerfileLines(certs []string, os OSFamily) []string {
	cfg := GetCACertConfig(os)
	var lines []string

	lines = append(lines, "# --- injected by whalevet: install ca-certificates package ---")
	lines = append(lines, "RUN "+cfg.InstallCmd)

	// Copy each certificate (source is basename, which must exist in build context root)
	lines = append(lines, "# --- injected by whalevet: copy custom CA certificates ---")
	var installed []string
	for _, cert := range certs {
		target := cfg.CertDir + "/" + CertTargetName(cert)
		installed = append(installed, target)
		lines = append(lines, fmt.Sprintf("COPY %s %s", filepath.Base(cert), target))
	}
	lines = append(lines, "# --- injected by whalevet: cover standalone bundles (e.g. /cacert.pem) ---")
	lines = append(lines, "RUN "+AppendExtraBundlesCmd(installed))

	// Update certificate store
	lines = append(lines, "# --- injected by whalevet: update certificate store ---")
	lines = append(lines, "RUN "+cfg.UpdateCmd)

	lines = append(lines, "# --- injected by whalevet: set CA bundle env vars ---")
	lines = append(lines, caCertEnvLines(cfg.BundlePath, cfg.TrustDir)...)

	return lines
}

// ExtraBundlePaths are well-known CA bundle files outside the OS store
// (e.g. curlimages/curl pins curl to /cacert.pem via CURL_CA_BUNDLE).
// Custom certs are appended when the file exists and lacks them.
var ExtraBundlePaths = []string{"/cacert.pem", "/etc/ssl/cert.pem"}

// shQuote quotes a string for POSIX sh single-quoted use.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// AppendExtraBundlesCmd returns a shell snippet appending the given installed
// cert files (absolute paths) to ExtraBundlePaths when present and missing.
// Idempotent: skips files whose first bytes already appear in the bundle.
func AppendExtraBundlesCmd(installedPaths []string) string {
	var sb strings.Builder
	sb.WriteString("for __b in")
	for _, b := range ExtraBundlePaths {
		sb.WriteString(" " + shQuote(b))
	}
	sb.WriteString("; do if [ -f \"$__b\" ]; then")
	sb.WriteString(" for __f in")
	if len(installedPaths) == 0 {
		sb.WriteString(" ")
	}
	for _, p := range installedPaths {
		sb.WriteString(" " + shQuote(p))
	}
	sb.WriteString("; do grep -qF \"$(head -c 64 \"$__f\")\" \"$__b\" || cat \"$__f\" >> \"$__b\"; done; fi; done")
	return sb.String()
}
