[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group | upper_first }}

{% for commit in commits -%}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }} ([commit {{ commit.id }}](https://github.com/mralves/whalevet/commit/{{ commit.id }}))
{% endfor -%}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^revert", group = "Reverts" },
  { message = "^docs", group = "Documentation" },
  { message = "^style", group = "Styles" },
  { message = "^chore", group = "Miscellaneous Chores" },
  { message = "^refactor", group = "Code Refactoring" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build System" },
  { message = "^ci", group = "Continuous Integration" },
  { message = ".*", group = "Other" },
]
